const data = {
    candles: [
        {
            _id: '1',
            name: 'Black & Whites xCandle',
            category: 'black vessel',
            image: '/images/p11.png',
            price:120,
            countInStock: 12,
            brand: 'SHEAN',
            rating: 5,
            numReviews: 13,
            description: 'high fragrance candle',
        },
        {
            _id: '2',
            name: 'APOTHECARY',
            category: 'Mason Jar',
            image: '/images/p10.png',
            price:140,
            countInStock: 100,
            brand: 'SHEAN',
            rating: 2.6,
            numReviews: 110,
            description: 'high fragrance candle',
        },
        {
            _id: '3',
            name: 'MEGA BLACK',
            category: 'Black Vessel',
            image: '/images/p9.png',
            price:90,
            countInStock: 10,
            brand: 'SHEAN',
            rating: 3.5,
            numReviews: 1,
            description: 'high fragrance candle',
        },
        {
            _id: '4',
            name: 'Luxury Signature',
            category: 'Luxury Candle',
            image: '/images/p3.jpg',
            price:120,
            countInStock: 12,
            brand: 'SHEAN',
            rating: 4.5,
            numReviews: 13,
            description: 'high fragrance candle',
        },
        {
            _id: '5',
            name: 'Black & White 2 Candle',
            category: 'black vessel',
            image: '/images/p4.jpg',
            price:120,
            countInStock: 12,
            brand: 'SHEAN',
            rating: 4.5,
            numReviews: 13,
            description: 'high fragrance candle',
        },
        {
            _id: '6',
            name: 'MUD',
            category: 'Mud Vessel',
            image: '/images/p5.jpg',
            price:120,
            countInStock: 90,
            brand: 'SHEAN',
            rating: 5,
            numReviews: 213,
            description: 'high fragrance candle',
        },
        {
            _id: '7',
            name: 'Kraft',
            category: 'Kraft Vessel',
            image: '/images/p6.jpg',
            price:120,
            countInStock: 120,
            brand: 'SHEAN',
            rating: 4,
            numReviews: 2,
            description: 'high fragrance candle',
        },
    ],
};


export default data;